export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const SUBMIT_ATTENDANCE = 'SUBMIT_ATTENDANCE';
export const ADD_ATTENDANCE = 'ADD_ATTENDANCE';
